services:
  geocoder:
    image: ghcr.io/natan-m64/traccar-geocoder:latest
    pull_policy: always
    environment:
      - PBF_URLS=https://download.geofabrik.de/south-america/brazil/nordeste-latest.osm.pbf
    ports:
      - "3000:3000"
    volumes:
      - geocoder-data:/data

volumes:
  geocoder-data:
